site_name: Lunar Lander
site_url: https://ocrobotix.github.io/lunarlander/
docs_dir: docs
exclude_patterns: ['.ipynb_checkpoints']
site_dir: site
use_directory_urls: false

theme:
  name: readthedocs
  navigation_depth: 5  # Number of header levels shown

extra_css:
  - css/extra.css
  - css/footer.css
  - css/theme_color.css
  - css/collapse.css

nav:
  - Home: index.md
  - INPUTS:
      - Vehicle Control: INPUTS/vehicle_inputs.ipynb
      - Lunar Environment: INPUTS/environment_inputs.ipynb
  - OUTPUTS:
      - Landing Ellipse: OUTPUTS/landing_ellipse.ipynb
      - Vehicle State: OUTPUTS/vehicle_state.ipynb
  - MODELS:
      - Apollo: MODELS/apollo.ipynb
      - Artemis: MODELS/artemis.ipynb
  - ASSUMPTIONS:
      - Mission: ASSUMPTIONS/mission_ass.ipynb
      - Modeling: ASSUMPTIONS/modeling_ass.ipynb
  - DATA:
      - Lunar: DATA/lunar_data.ipynb
      - Vehicle: DATA/vehicle_data.ipynb
  - APPENDIX:
      - Glossary: APPENDIX/glossary.ipynb
      - Resources: APPENDIX/resources.ipynb
      - FAQs/UAQs: APPENDIX/faqs.ipynb
      - Lunar Missions: APPENDIX/lunar_missions.ipynb
      - Sandbox: APPENDIX/sandbox.md
  - FEEDBACK:
      - Blog: FEEDBACK/blog.md
      - Comment: FEEDBACK/comment.md
      - Upload: FEEDBACK/upload.md

  #- z_clipboard:
  #    - Collapse: z_clipboard/collapse.md
  #    - Collapse2: z_clipboard/collapse-mkdocs.md
  #    - Headings: z_clipboard/head.md
  #    - Table of Contents: z_clipboard/toc.md
  #    - Image & Video: z_clipboard/iframe-image-video.md
  #    - Navigate: z_clipboard/navigate.md
  #    - Miscellaneous: z_clipboard/misc.md
  #    - fonts: z_clipboard/fonts.md
  #    - upload: z_clipboard/upload.md

plugins:
  - search
  - mkdocs-jupyter
  - git-revision-date
  # - blogging
  - blog:
      path: FEEDBACK
      tags: true
      archive: true
      rss: false

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - pymdownx.details
