site_name: Lunar Lander
site_url: https://ocrobotix.github.io/lunarlander/

theme:
  name: readthedocs
  navigation_depth: 5  # Number of header levels shown

extra_css:
  - css/extra.css
  - css/footer.css
  - css/theme_color.css

nav:
- INPUTS:
  - Vehicle Parameters: INPUTS/vehicle.ipynb
  - Lunar Environment Variables: INPUTS/environment.ipynb

- OUTPUTS:
  - Vehicle State: OUTPUTS/state.ipynb
  - Landing Ellipse: OUTPUTS/ellipse.ipynb
  - Touchdown Location: OUTPUTS/touchdown.ipynb

- MODELS:
  - Apollo: MODELS/apollo.ipynb
  - Artemis: MODELS/artemis.ipynb

- APPENDIX:
  - Glossary: APPENDIX/glossary.md
  - References: APPENDIX/references.md
  - FAQs: APPENDIX/faqs.md


- Blog: blog.md
- About: about.md
- Template: template1.md


- TEMPLATES:
  - Headings: TEMPLATES/head.md
  - Table of Contents: TEMPLATES/toc.md
  - Image & Video: TEMPLATES/image-video.md
  - Links & ID: TEMPLATES/links-id.md
  - Miscellaneous: TEMPLATES/misc.md



plugins:
  - search
  - mkdocs-jupyter
  - git-revision-date
  - blogging

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
