site_name: Lunar Lander
site_url: https://ocrobotix.github.io/lunarlander/
docs_dir: docs
exclude_patterns: ['.ipynb_checkpoints']
site_dir: site
use_directory_urls: false

theme:
  name: readthedocs
  navigation_depth: 5  # Number of header levels shown

extra_css:
  - css/extra.css
  - css/footer.css
  - css/theme_color.css
  - css/collapse.css

nav:
- INPUTS:
  - Vehicle Parameters: INPUTS/vehicle_inputs.ipynb
  - Lunar Environment Variables: INPUTS/environment_inputs.ipynb

- OUTPUTS:
  - Landing Ellipse: OUTPUTS/landing_ellipse.ipynb
  - Vehicle State: OUTPUTS/vehicle_state.ipynb

- MODELS:
  - Apollo: MODELS/apollo.ipynb
  - Artemis: MODELS/artemis.ipynb

- APPENDIX:
  - Glossary: APPENDIX/glossary.ipynb
  - FAQs: APPENDIX/faqs.ipynb
  - References: APPENDIX/references_resources.ipynb
  - Sandbox: APPENDIX/sandbox.md

- Blog: DO.md
#- About: about.md


#- SANDBOX:
  #- Exploitation: SANDBOX/__.md
  #- Expedition: SANDBOX/__.md
  #- Exploration: SANDBOX/__.md
#- TEMPLATES:
  #- Collapse: TEMPLATES/collapse.md
  #- Collapse2: TEMPLATES/collapse-mkdocs.md
#  - Headings: TEMPLATES/head.md
#  - Table of Contents: TEMPLATES/toc.md
#  - Image & Video: TEMPLATES/iframe-image-video.md
#  - Navigate: TEMPLATES/navigate.md
#  - Miscellaneous: TEMPLATES/misc.md


plugins:
  - search
  - mkdocs-jupyter
  - git-revision-date
  - blogging

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - pymdownx.details