site_name: Lunar Lander
site_url: https://ocrobotix.github.io/lunarlander/
docs_dir: docs
site_dir: site
use_directory_urls: false


theme:
  name: readthedocs
  navigation_depth: 5  # Number of header levels shown

extra_css:
  - css/extra.css
  - css/footer.css
  - css/theme_color.css
  - css/collapse.css

nav:
- INPUTS:
  - Vehicle Parameters: INPUTS/vehicle.ipynb
  - Environment Variables: INPUTS/environment.ipynb

- OUTPUTS:
  - Landing Ellipse: OUTPUTS/ellipse.ipynb
  - Touchdown Location: OUTPUTS/touchdown.ipynb
  - Vehicle State: OUTPUTS/state.ipynb

- MODELS:
  - Apollo: MODELS/apollo.ipynb
  - Artemis: MODELS/artemis.ipynb

- APPENDIX:
  - Glossary: APPENDIX/glossary.md
  - References: APPENDIX/references.md
  - FAQs: APPENDIX/faqs.md

- Blog: blog.md
#- About: about.md
#- Template: template1.md

- TEMPLATES:
  - Collapse: TEMPLATES/collapse.md
  - Collapse2: TEMPLATES/collapse-mkdocs.md
#  - Headings: TEMPLATES/head.md
#  - Table of Contents: TEMPLATES/toc.md
#  - Image & Video: TEMPLATES/iframe-image-video.md
#  - Navigate: TEMPLATES/navigate.md
#  - Miscellaneous: TEMPLATES/misc.md

plugins:
  - search
  - mkdocs-jupyter
  - git-revision-date
  - blogging

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - pymdownx.details


